/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=CloudflareBindings` (hash: 2fefe14895c49e47adeb0076e4a48cd9)
interface __BaseEnv_CloudflareBindings {
	RAW_ARTIFACTS: R2Bucket;
	DB: D1Database;
	INGEST_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	SURF_REGION: "norcal";
	SURF_USER_AGENT: "surf-self-hosted/1.0 (+https://github.com/aylee/surf)";
	GEMINI_API_KEY: string;
	FORECAST_BRIEF_ENABLED: string;
	FORECAST_BRIEF_AGENT: DurableObjectNamespace<import("./worker/index").ForecastBriefAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "ForecastBriefAgent";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SURF_REGION" | "SURF_USER_AGENT" | "GEMINI_API_KEY" | "FORECAST_BRIEF_ENABLED">> {}
}
