/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=CloudflareBindings` (hash: 36520676ce377d5d0c7c7ab371e8d153)
interface __BaseEnv_CloudflareBindings {
	RAW_ARTIFACTS: R2Bucket;
	DB: D1Database;
	INGEST_QUEUE: Queue;
	NARRATIVE_QUEUE: Queue;
	NARRATIVE_FALLBACK_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	SURF_REGION: "norcal";
	SURF_USER_AGENT: "surf-self-hosted/1.0 (+https://github.com/aylee/surf)";
	SURF_SOURCE_REVISION: "0000000000000000000000000000000000000000";
	SURF_WORKER_RUNTIME_DIGEST: "0000000000000000000000000000000000000000000000000000000000000000";
	SURF_CLIENT_BUILD_DIGEST: "0000000000000000000000000000000000000000000000000000000000000000";
	NARRATIVE_FALLBACK_MODEL: "gemini-3.6-flash";
	NARRATIVE_FALLBACK_DELAY_SECONDS: "600";
	NARRATIVE_FALLBACK_DAILY_CAP: "4";
	NARRATIVE_FALLBACK_ROLLING_31_DAY_CAP: "100";
	GEMINI_API_KEY: string;
	FORECAST_BRIEF_ENABLED: string;
	NARRATIVE_ENABLED: string;
	NARRATIVE_RESULT_TOKEN: string;
	FORECAST_BRIEF_AGENT: DurableObjectNamespace<import("./worker/index").ForecastBriefAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "ForecastBriefAgent";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SURF_REGION" | "SURF_USER_AGENT" | "SURF_SOURCE_REVISION" | "SURF_WORKER_RUNTIME_DIGEST" | "SURF_CLIENT_BUILD_DIGEST" | "NARRATIVE_FALLBACK_MODEL" | "NARRATIVE_FALLBACK_DELAY_SECONDS" | "NARRATIVE_FALLBACK_DAILY_CAP" | "NARRATIVE_FALLBACK_ROLLING_31_DAY_CAP" | "GEMINI_API_KEY" | "FORECAST_BRIEF_ENABLED" | "NARRATIVE_ENABLED" | "NARRATIVE_RESULT_TOKEN">> {}
}
